In [190]:
import pandas as pd
import numpy as np
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.externals import joblib
from sklearn import tree

game_data = pd.read_csv('vgsales.csv')

game_data.head(18)

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,1,Wii Sports,Wii,2006.0,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74
1,2,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24
2,3,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82
3,4,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00
4,5,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37
5,6,Tetris,GB,1989.0,Puzzle,Nintendo,23.20,2.26,4.22,0.58,30.26
6,7,New Super Mario Bros.,DS,2006.0,Platform,Nintendo,11.38,9.23,6.50,2.90,30.01
7,8,Wii Play,Wii,2006.0,Misc,Nintendo,14.03,9.20,2.93,2.85,29.02
8,9,New Super Mario Bros. Wii,Wii,2009.0,Platform,Nintendo,14.59,7.06,4.70,2.26,28.62
9,10,Duck Hunt,NES,1984.0,Shooter,Nintendo,26.93,0.63,0.28,0.47,28.31
10,11,Nintendogs,DS,2005.0,Simulation,Nintendo,9.07,11.00,1.93,2.75,24.76
11,12,Mario Kart DS,DS,2005.0,Racing,Nintendo,9.81,7.57,4.13,1.92,23.42
12,13,Pokemon Gold/Pokemon Silver,GB,1999.0,Role-Playing,Nintendo,9.00,6.18,7.20,0.71,23.10
13,14,Wii Fit,Wii,2007.0,Sports,Nintendo,8.94,8.03,3.60,2.15,22.72
14,15,Wii Fit Plus,Wii,2009.0,Sports,Nintendo,9.09,8.59,2.53,1.79,22.00
15,16,Kinect Adventures!,X360,2010.0,Misc,Microsoft Game Studios,14.97,4.94,0.24,1.67,21.82
16,17,Grand Theft Auto V,PS3,2013.0,Action,Take-Two Interactive,7.01,9.27,0.97,4.14,21.40
17,18,Grand Theft Auto: San Andreas,PS2,2004.0,Action,Take-Two Interactive,9.43,0.40,0.41,10.57,20.81

In [176]:
#inspect data
game_data.shape

(16598, 11)

In [177]:
game_data.describe()
#Problem with Year column

,Rank,Year,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
count,16598.000000,16327.000000,16598.000000,16598.000000,16598.000000,16598.000000,16598.000000
mean,8300.605254,2006.406443,0.264667,0.146652,0.077782,0.048063,0.537441
std,4791.853933,5.828981,0.816683,0.505351,0.309291,0.188588,1.555028
min,1.000000,1980.000000,0.000000,0.000000,0.000000,0.000000,0.010000
25%,4151.250000,2003.000000,0.000000,0.000000,0.000000,0.000000,0.060000
50%,8300.500000,2007.000000,0.080000,0.020000,0.000000,0.010000,0.170000
75%,12449.750000,2010.000000,0.240000,0.110000,0.040000,0.040000,0.470000
max,16600.000000,2020.000000,41.490000,29.020000,10.220000,10.570000,82.740000

In [191]:
game_data.isnull().sum()

Rank              0
Name              0
Platform          0
Year            271
Genre             0
Publisher        58
NA_Sales          0
EU_Sales          0
JP_Sales          0
Other_Sales       0
Global_Sales      0
dtype: int64

In [193]:
game_data[game_data.Year.isnull()]

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
179,180,Madden NFL 2004,PS2,NaN,Sports,Electronic Arts,4.26,0.26,0.01,0.71,5.23
377,378,FIFA Soccer 2004,PS2,NaN,Sports,Electronic Arts,0.59,2.36,0.04,0.51,3.49
431,432,LEGO Batman: The Videogame,Wii,NaN,Action,Warner Bros. Interactive Entertainment,1.86,1.02,0.00,0.29,3.17
470,471,wwe Smackdown vs. Raw 2006,PS2,NaN,Fighting,NaN,1.57,1.02,0.00,0.41,3.00
607,608,Space Invaders,2600,NaN,Shooter,Atari,2.36,0.14,0.00,0.03,2.53
624,625,Rock Band,X360,NaN,Misc,Electronic Arts,1.93,0.34,0.00,0.21,2.48
649,650,Frogger's Adventures: Temple of the Frog,GBA,NaN,Adventure,Konami Digital Entertainment,2.15,0.18,0.00,0.07,2.39
652,653,LEGO Indiana Jones: The Original Adventures,Wii,NaN,Action,LucasArts,1.54,0.63,0.00,0.22,2.39
711,713,Call of Duty 3,Wii,NaN,Shooter,Activision,1.19,0.84,0.00,0.23,2.26
782,784,Rock Band,Wii,NaN,Misc,MTV Games,1.35,0.56,0.00,0.20,2.11
1126,1128,Call of Duty: Black Ops,PC,NaN,Shooter,Activision,0.58,0.81,0.00,0.24,1.63
1133,1135,Rock Band,PS3,NaN,Misc,Electronic Arts,0.99,0.41,0.00,0.22,1.62
1303,1305,Triple Play 99,PS,NaN,Sports,NaN,0.81,0.55,0.00,0.10,1.46
1433,1435,LEGO Harry Potter: Years 5-7,Wii,NaN,Action,Warner Bros. Interactive Entertainment,0.76,0.47,0.00,0.13,1.36
1498,1500,LEGO Batman: The Videogame,PSP,NaN,Action,Warner Bros. Interactive Entertainment,0.57,0.46,0.00,0.28,1.32
1513,1515,Adventure,2600,NaN,Adventure,Atari,1.21,0.08,0.00,0.01,1.30
1585,1587,Combat,2600,NaN,Action,Atari,1.17,0.07,0.00,0.01,1.25
1649,1651,NASCAR Thunder 2003,PS2,NaN,Racing,Unknown,0.60,0.46,0.00,0.16,1.22
1697,1699,Hitman 2: Silent Assassin,XB,NaN,Action,Eidos Interactive,0.76,0.38,0.00,0.05,1.19
1837,1839,Rock Band,PS2,NaN,Misc,Electronic Arts,0.71,0.06,0.00,0.35,1.11
1990,1992,Legacy of Kain: Soul Reaver,PS,NaN,Action,Eidos Interactive,0.58,0.40,0.00,0.07,1.04
2019,2021,Donkey Kong Land III,GB,NaN,Platform,Nintendo,0.68,0.31,0.00,0.04,1.03
2086,2088,LEGO Harry Potter: Years 5-7,X360,NaN,Action,Warner Bros. Interactive Entertainment,0.51,0.39,0.00,0.09,0.99
2113,2115,Air-Sea Battle,2600,NaN,Shooter,Atari,0.91,0.06,0.00,0.01,0.98
2114,2116,Suikoden III,PS2,NaN,Role-Playing,Unknown,0.29,0.23,0.38,0.08,0.98
2134,2136,Yakuza 4,PS3,NaN,Action,Sega,0.15,0.14,0.63,0.05,0.97
2145,2147,LEGO Harry Potter: Years 5-7,PS3,NaN,Action,Warner Bros. Interactive Entertainment,0.36,0.45,0.00,0.16,0.97
2173,2175,Wheel of Fortune,PS2,NaN,Misc,Unknown,0.47,0.36,0.00,0.12,0.95
2286,2288,Namco Museum,XB,NaN,Misc,Unknown,0.77,0.11,0.00,0.04,0.91
2295,2297,Rhythm Heaven,Wii,NaN,Misc,Unknown,0.13,0.00,0.77,0.01,0.90
...,...,...,...,...,...,...,...,...,...,...,...
15197,15200,Saint,Wii,NaN,Shooter,Unknown,0.02,0.00,0.00,0.00,0.02
15208,15211,Steal Princess,DS,NaN,Platform,Unknown,0.02,0.00,0.00,0.00,0.02
15261,15264,Mario Tennis,3DS,NaN,Sports,NaN,0.00,0.00,0.02,0.00,0.02
15316,15319,Runaway: A Twist of Fate,DS,NaN,Adventure,Focus Home Interactive,0.00,0.02,0.00,0.00,0.02
15476,15479,Yu-Gi-Oh! 5D's Wheelie Breakers (JP sales),Wii,NaN,Racing,Unknown,0.00,0.00,0.02,0.00,0.02
15579,15582,Cabela's Alaskan Adventure,PS2,NaN,Sports,Unknown,0.01,0.01,0.00,0.00,0.02
15606,15609,Writing and Speaking Beautiful Japanese DS,DS,NaN,Misc,Unknown,0.00,0.00,0.02,0.00,0.02
15652,15655,Virtua Quest,PS2,NaN,Role-Playing,Unknown,0.01,0.01,0.00,0.00,0.02
15697,15700,Shonen Jump's Yu-Gi-Oh! GX Card Almanac,DS,NaN,Misc,Konami Digital Entertainment,0.00,0.00,0.02,0.00,0.02
15717,15720,Without Warning,XB,NaN,Shooter,Capcom,0.01,0.00,0.00,0.00,0.02
15739,15742,Football Manager 2007,X360,NaN,Sports,Sega,0.00,0.01,0.00,0.00,0.02
15811,15814,Ferrari: The Race Experience,Wii,NaN,Racing,System 3 Arcade Software,0.00,0.01,0.00,0.00,0.02
15865,15868,PDC World Championship Darts 2008,DS,NaN,Sports,Unknown,0.01,0.00,0.00,0.00,0.02
15876,15879,Dinotopia: The Sunstone Odyssey,GC,NaN,Action,Unknown,0.01,0.00,0.00,0.00,0.02
15878,15881,Dance! It's Your Stage,Wii,NaN,Misc,DTP Entertainment,0.00,0.01,0.00,0.00,0.02
15900,15903,Jet Impulse,DS,NaN,Simulation,Nintendo,0.00,0.00,0.02,0.00,0.02
15915,15918,Dream Dancer,DS,NaN,Misc,NaN,0.01,0.00,0.00,0.00,0.02
16057,16060,PDC World Championship Darts 2008,PSP,NaN,Sports,Oxygen Interactive,0.01,0.00,0.00,0.00,0.01
16058,16061,WRC: FIA World Rally Championship,PC,NaN,Racing,Black Bean Games,0.00,0.01,0.00,0.00,0.01
16065,16068,Aquaman: Battle for Atlantis,XB,NaN,Action,Unknown,0.01,0.00,0.00,0.00,0.01
16191,16194,Homeworld Remastered Collection,PC,NaN,Strategy,NaN,0.00,0.01,0.00,0.00,0.01
16194,16197,Shorts,DS,NaN,Platform,Unknown,0.01,0.00,0.00,0.00,0.01
16198,16201,AKB1/48: Idol to Guam de Koishitara...,X360,NaN,Misc,NaN,0.00,0.00,0.01,0.00,0.01
16229,16232,Brothers in Arms: Furious 4,X360,NaN,Shooter,NaN,0.01,0.00,0.00,0.00,0.01
16246,16249,Agarest Senki: Re-appearance,PS3,NaN,Role-Playing,Idea Factory,0.00,0.00,0.01,0.00,0.01
16307,16310,Freaky Flyers,GC,NaN,Racing,Unknown,0.01,0.00,0.00,0.00,0.01
16327,16330,Inversion,PC,NaN,Shooter,Namco Bandai Games,0.01,0.00,0.00,0.00,0.01
16366,16369,Hakuouki: Shinsengumi Kitan,PS3,NaN,Adventure,Unknown,0.01,0.00,0.00,0.00,0.01
16427,16430,Virtua Quest,GC,NaN,Role-Playing,Unknown,0.01,0.00,0.00,0.00,0.01
16493,16496,The Smurfs,3DS,NaN,Action,Unknown,0.00,0.01,0.00,0.00,0.01

In [197]:
game_data = game_data.dropna(subset=['Year'], how = 'all')

game_data.shape

(16327, 11)

In [198]:
X = game_data.drop(columns=['Name', 'Platform','Genre','Publisher','NA_Sales', 'EU_Sales', 'Other_Sales','JP_Sales', 'Global_Sales'])
y = game_data.drop(columns=['Rank','Name', 'Platform','Year','Genre','Publisher', 'EU_Sales', 'Other_Sales','JP_Sales', 'Global_Sales'])

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25)

In [199]:
#Inspect training sets
X_train

        Rank    Year
16225  16228  2007.0
2590    2592  2013.0
9331    9333  2003.0
2156    2158  2006.0
8087    8089  2016.0
1113    1115  2004.0
16360  16363  2013.0
7980    7982  2007.0
3572    3574  2006.0
8265    8267  2003.0
8657    8659  2016.0
14729  14732  2006.0
2454    2456  2010.0
3624    3626  2006.0
5015    5017  2016.0
1980    1982  2007.0
9738    9740  1997.0
10776  10778  2007.0
195      196  2006.0
8000    8002  2012.0
9003    9005  2005.0
7700    7702  2002.0
7189    7191  2006.0
13273  13275  2013.0
9589    9591  2008.0
16138  16141  2002.0
13425  13427  2006.0
8291    8293  2008.0
11879  11881  2010.0
7916    7918  2007.0
...      ...     ...
6652    6654  2009.0
10642  10644  1999.0
240      241  2006.0
12634  12636  2012.0
1780    1782  1997.0
2175    2177  2005.0
9876    9878  1998.0
13616  13618  2006.0
12720  12722  2004.0
286      287  2007.0
9407    9409  2002.0
12219  12221  2011.0
15843  15846  2010.0
10999  11001  2011.0
524      525  2003.0
5226    5228  2015.0
12264  12266  2014.0
10522  10524  2008.0
2986    2988  2007.0
15571  15574  2009.0
4401    4403  2008.0
5649    5651  2005.0
490      491  2006.0
10782  10784  2008.0
10350  10352  2005.0
3973    3975  2012.0
2763    2765  2006.0
12641  12643  2007.0
7894    7896  2010.0
3667    3669  1997.0

[12245 rows x 2 columns]

In [200]:
y_train

       NA_Sales
16225      0.00
2590       0.39
9331       0.10
2156       0.30
8087       0.06
1113       0.80
16360      0.00
7980       0.17
3572       0.28
8265       0.13
8657       0.00
14729      0.00
2454       0.56
3624       0.42
5015       0.15
1980       0.45
9738       0.07
10776      0.00
195        3.81
8000       0.10
9003       0.11
7700       0.00
7189       0.19
13273      0.00
9589       0.12
16138      0.01
13425      0.00
8291       0.08
11879      0.00
7916       0.15
...         ...
6652       0.15
10642      0.06
240        3.63
12634      0.00
1780       0.00
2175       0.36
9876       0.07
13616      0.01
12720      0.03
286        2.13
9407       0.10
12219      0.06
15843      0.00
10999      0.09
524        1.32
5226       0.23
12264      0.02
10522      0.00
2986       0.21
15571      0.02
4401       0.18
5649       0.29
490        0.87
10782      0.09
10350      0.00
3973       0.22
2763       0.00
12641      0.05
7894       0.14
3667       0.00

[12245 rows x 1 columns]

In [201]:
model = DecisionTreeClassifier()
model.fit(X_train, y_train)
predictions = model.predict(X_test)


score = accuracy_score(y_test, predictions)

ValueError: Unknown label type: 'continuous'

In [148]:
score

NameError: name 'score' is not defined

In [ ]:
joblib.dump(model, 'NAsales_predictor.joblib')

In [ ]:
model = joblib.load('NAsales_predictor.joblib')

In [ ]:
tree.export_graphviz(model, out_file='NAsales_predictor.joblib',
                     feature_names=['Rank','Year'],
                    class_names=sorted(y.unique()),
                    label='all',
                    rounded=True,
                    filled=True)